### ISSUE TITLE
API key not necessary?

### ISSUE THREAD

**Issue by Beheer007** [lreading/smtp-to-gotify-docker#1]
When using your SMTP docker for Gotify I can send messages from my local network without having to specify a valid API key (that I defined in de docker-compose environment variable for smtp-to-gotify-docker). Is this by design since I am on the local network or am I doing something wrong?

**Comment by lreading** [comment]
That is very much **not** intentional, I'll have a look and report back! :sweat_smile:

**Comment by lreading** [comment]
Thanks for bringing this up @Beheer007! :beers: 

Turns out I had a line leftover from debugging that wasn't supposed to be there. :disappointed: I've updated the latest tag (and the code is updated as well), and I also created a new tag of imoshtokill/smtp-to-gotify-docker:2.0.0 if you'd prefer to use that instead.

Cheers, and thanks again!
